baseURL = "https://blog.evercoding.net"
disablePathToLower = false
languageCode = "zh-cn"
title = "天外天"

hasCJKLanguage = true

# disqusShortName = "evercoding"
googleAnalytics = "UA-54098391-1"

theme = "ink"
# syntax highlight
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = false

paginate = 10

[Permalinks]
    post = "/post/:filename"

[params]
    # see https://gohugo.io/functions/format/
    dateFormat = "2006.1.2"

    github = "ieverx"

[params.utteranc]
    enabled = true
    repo = "ieverx/ieverx.github.io"
    issueTerm = "pathname"
    label = "comment"
    theme = "github-light"

[[params.nav]]
name = "home"
url = "/"

[[params.nav]]
name = "tags"
url = "/tags"

[[params.nav]]
name = "message"
url = "/message-board"

[[params.nav]]
name = "github"
github = true

[blackfriday]
    extensions = ["hardLineBreak", "joinLines"]
