name: Deploy Github Pages

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: source
      - name: Build and deploy
        uses: ieverx/zola-deploy-action@v0.15.2
        env:
          PAGES_BRANCH: master
          BUILD_DIR: .
          TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
          ZOLA_MODE: production
